# Generated by Django 5.0 on 2023-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('quantity_sqft', models.FloatField(default=0.0)),
                ('quantity_pcs', models.FloatField(default=0.0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
