# Generated by Django 5.0 on 2023-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_pcs',
            field=models.IntegerField(default=0),
        ),
    ]
